### ISSUE TITLE
v4.0.0 Roadmap

### ISSUE THREAD

**Issue by therealsujitk** [therealsujitk/android-vtop-chennai#11]
Here are a list of things to be completed for the v4.0 release (Inspired by Android 12).

- [x] Rename application (VTOP --> VIT Student)
- [x] Redesign application logo
- [x] Redesign login activity
- Redesign main activity
  - Home fragment with timetable, overall attendance, overall credits, cgpa
    - [x] Fragment to view spotlight
    - [x] Bottom cord to fiew more info on a course when clicked in the timetable
  - [x] Performance fragment with marks and calculated weightages based on credits
  - [x] Assignments fragment (#4)
  - Profile fragment with everything else and application settings
    - [x] Fragment to view courses, faculties and attendance
    - [ ] Fragment to view messages (#7)
    - [x] Fragment to view staff
    - [x] Fragment to view receipts
    - [x] Option to sync data
    - [x] Option to change theme
    - [x] Option to view notification settings
    - [x] Option to view privacy policy
    - [x] Option to send feedback
    - [x] Option to share app
    - Option to sign out
      - [x] Option to sign out of VIT Student
      - [x] Option to sign out of Moodle
- [x] Redesign login activity
- [x] Convert the VTOP download algorithm to a foreground service
- Display a vector image for empty state
  - [x] No classes for the day in timetable
  - [x] No announcements, no receipts, no messages
  - [x] No marks released
  - [x] No assignments due
  - [x] No registered courses, no staff into
  - [x] Error while retrieving data
- [x] Display badges for unread data (#5)

<hr>

Non-application related tasks.

- [x] Add Privacy Policy
- [x] Add CONTRIBUTING.md, CODE_OF_CONDUCT.md and ISSUE_TEMPLATE.md
